#!/bin/bash
#
#
function loadparams() {
    local mpt=""
    [ "$SDMNSPAWN" == "Phase0" ] && mpt=$SDMPT
    source $mpt/etc/sdm/sdm-readparams
}
# $1 is the phase: "0", "1", or "post-install"

#
#
phase=$1
pfx="$(basename $0)"

if [ $phase == "0" ]
then
    #
    # Phase 0
    #
    loadparams
    logtoboth "* $pfx Phase 0"

    mkdir -p $SDMPT/home/Jamie
    cp -R ../Server/models $SDMPT/home/Jamie
    cp ../Server/send_reminder.py $SDMPT/home/Jamie
    cp ../Server/systemd/* $SDMPT/etc/systemd/system

    logtoboth "* $pfx Phase 0 Completed"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1
    #
    loadparams
    logtoboth "* $pfx Phase 1"
    logfreespace "at start of $pfx Phase 1"
    #
    systemctl enable draft_check.timer
    apt install -y postgresql
    su postgres
    createuser jamie -d -s
    #
    logfreespace "at end of $pfx Phase 1"
    logtoboth "* $pfx Phase 1 Completed"
else
    #
    # Post-install edits
    #
    loadparams
    logtoboth "* $pfx Custom Phase post-install"
    logfreespace "at start of $pfx Custom Phase post-install"
    #
    apt install -y python3-pip
    pip3 install SQLAlchemy
    pip3 install psycopg2-binary
    #
    logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* $pfx Custom Phase post-install Completed"
fi